export const languages = {
  uz: {
    cancel: "Bekor qilish",
    consumerAddress: "Mijoz manzili",
    allPrice: "Jami narxi",
    status: "Status",
    date: "Sanasi",
    quantity: "Miqdori",
    consumer: "Mijoz",
    orderInfo: "Buyurtma haqida ma`lumot",
    consumerNumber: "Telefon nomeri",
    paymentMethod: "To`lov turi",
    page: "Sahifa",
    enter: "kiriting",
    url: "URL ni",
    success: "muvaffaqiyatli",
    update: "yangilandi",
    add: "Qo'shish",
    name: "Nomi",
    description: "tavsifi",
    edit: "Tahrirlash",
    delete: "O`chirish",
    changeUrl: "Bu URL band, iltimos URL ni o`zgartiring!",
    main: "Asosiy",
    yes: "Ha",
    no: "yo'q",
    image: "Rasm",
    save: "Saqlash",
    users: "Foydalanuvchilar",
    userName: "Foydalanuvchi ismi",
    userPhone: "Foydalanuvchi raqami",
    postsCount: "Joylagan postlar soni",
    noName: "Ismsiz",
    ads: "E'lonlar",
    type: "Turi",
    arrives_at: "Yetib keladi",
    leaves_at: "Jo`nab ketadi",
    from_region: "Qayerdan",
    to_region: "Qayerga",
    parcel: "Posilka",
    courier: "Kuryer",
    view: "Ko'rish",
    dashboard: "Statistika",
    refresh: "Yangilash",
    company: "Kompaniya",
    company_slider: "Kompaniya Slayderi",
    news: "Yangiliklar",
    slider: "Slayder",
    services: "Xizmatlar",
    team: "Jamoa",
    logo: "Logo",
    phone: "Raqami",
    action: "Action",
    title: "Sarlavha",
    title_ru: "Sarlavha Ruscha",
    subtitle: "Subtitr",
    subtitle_ru: "Subtitr Ruschasi",
    intro: "Kirish",
    intro_ru: "Kirish Ruschasi",
    author: "Avtor",
    slug: "Slug",
    submit: "Saqlash",
    content: "Tarkib",
    content_ru: "Tarkib Ruschasi",
    description: "Tavsif",
    job: "Vazifasi",
    job_ru: "Vazifasi Ruschasi",
    link: "Link",
    feature: "Afzallik",
    address: "Manzili",
    address_ru: "Manzili Ruscha",
    name_ru: "Ruscha nomi",
    companyFeatureTitle: "Kompaniya xususiyati nomi",
    companyFeatureSubtitle: "Kompaniya xususiyati subtitlesi",
    telegram: "Telegram",
    instagram: "Instagram",
    facebook: "Facebook",
    youtube: "Youtube",
    counts: "Soni",
    video: "Video",
  },
  ru: {
    cancel: "Отмена",
    consumerAddress: "Адрес клиента",
    allPrice: "Итоговая цена",
    status: "Статус",
    date: "Дата",
    quantity: "Количество",
    consumer: "Клиент",
    orderInfo: "Запросить информацию",
    consumerNumber: "Номер телефона",
    paymentMethod: "Тип платежа",
    page: "Страница",
    enter: "войти",
    url: "URL-адрес",
    success: "успешно",
    update: "обновлена",
    add: "Добавление",
    name: "Hазвание",
    description: "описание",
    edit: "Редактировать",
    delete: "Удалить",
    changeUrl: "Этот URL-адрес занят, пожалуйста, измените URL-адрес!",
    main: "Главный",
    yes: "Да",
    no: "Нет",
    image: "Картина",
    save: "Сохранять",
    users: "Пользователи",
    userName: "Имя пользователя",
    userPhone: "Номер пользователя",
    postsCount: "Количество размещенных постов",
    noName: "Безымянный",
    ads: "Объявления",
    type: "Тип",
    arrives_at: "Он прибывает",
    leaves_at: "Он уходит",
    from_region: "Где",
    to_region: "Где",
    parcel: "Посылка",
    courier: "Курьер",
    view: "Видеть",
    dashboard: "Статистика",
    refresh: "Обновить",
    company: "Компания",
    company_slider: "Слайдер компании",
    news: "Новости",
    slider: "Слайдер",
    services: "Услуги",
    team: "Команда",
    logo: "Логотип",
    phone: "Hомер",
    action: "Действие",
    title: "Заголовок",
    title_ru: "Заголовок на русском",
    subtitle: "Подзаголовок",
    subtitle_ru: "Подзаголовок на русском",
    intro: "Введение",
    intro_ru: "Введение на русском",
    author: "Автор",
    slug: "Слуг",
    submit: "Разместить",
    content: "Содержание",
    content_ru: "Содержание на русском",
    description: "Описание",
    job: "Должньост",
    job: "Должньост на русском",
    link: "Ссылка",
    feature: "Особенность",
    address: "Аддресс",
    address_ru: "Аддресс на русском",
    name_ru: "Hазвание на русском",
    companyFeatureTitle: "Название функции компании",
    companyFeatureSubtitle: "Подзаголовок функции компании",
    telegram: "Телеграм",
    instagram: "Инстаграм",
    facebook: "Фейсбук",
    youtube: "Ютуб",
    counts: "Счет",
    video: "Видео",
  },
};
